### ISSUE TITLE
Add interactive element to give feedback or share comments

### ISSUE THREAD

**Issue by EmmanuelDrouin** [liteflow-labs/docs#57]
We should add an interractive element (button or other) that will allow user to share their comments and feedback with us.

I know there is some platforms/technologie that we could use to do so.

It could be something useful for us to gather precious feedback about what's not clear or what's not working. (That could be something useful for the console also)

Related to this feedback: [feedback video](https://www.youtube.com/watch?v=IIlKw4V07DY&t=29s)

**Comment by antho1404** [comment]
This seems a bit overkill and distracting. I really think the "edit the page" at the bottom is sufficient and this is quite common in documentation. We still need to fix the issue related to that #53
