### ISSUE TITLE
Improve "Why use the Liteflow Framework?" section

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/docs#8]
I received really good feedback from @ThomasKientz mostly concerning the following section on the docs:

> Why use the Liteflow Framework?
> The tools within the Framework:
> 
> Create processes based on custom or existing services
> Create and manage services for an application
> Manage communications between any services
> Manage the security and isolation of services
> Route the various tasks and events between services

The summary of the feedbacks are:
- the content doesn't answer "Why", but answers the "How"
- add use cases
- explain the concept of liteflow (but should be on the landing page)
  - zero code
  - serverless
  - create apps using existing services
  - if a service is missing: create your own and get rewards
- we should adjust the vocabulary and ideas to the target audience
  - we should not use "blockchain"
  - we should simplify the explanation ("what is the MESG Engine", etc..)

**Comment by antho1404** [comment]
This section might not even be needed and could be removed if it doesn't provide much value.

From @NicolasMahe https://github.com/liteflow-labs/docs/pull/11#discussion_r424194382

**Comment by EmmanuelDrouin** [comment]
I agree with Nicolas feedback. Not sure we really need this section. Could be better to have that as a reminder in a introduction page of the docs instead of the get started.

**Comment by EmmanuelDrouin** [comment]
@NicolasMahe @antho1404 so what's the decision here? Do we keep it or not?
I would like to close this issue if it's not relevant anymore

**Comment by antho1404** [comment]
Agree to remove it, this doesn't provide much value here but we should make sure that the user can find some context so have a link on the website somewhere

**Comment by antho1404** [comment]
fixed by https://github.com/liteflow-labs/docs/pull/13
